/* empty css                      */import{a as o}from"./assets/vendor-2b35cb0d.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const a="https://your-energy.b.goit.study/api/",f={bodypart:"Body parts",muscles:"Muscles",equipment:"Equipment"};class p{constructor({filter:s="muscles",subFilter:i="",keyword:n="",page:e=1,limit:t=8}){this.filter=s,this.subFilter=i,this.keyword=n,this.page=e,this.limit=t}async getFilters(){return(await o.get(`${a}filters`,{params:{filter:f[this.filter],page:this.page,limit:this.limit}})).data}async getExercises(){return(await o.get(`${a}exercises`,{params:{[this.filter]:this.subFilter,keyword:this.keyword,page:this.page,limit:this.limit}})).data}async getExerciseById(s){return(await o.get(`${a}exercises/${s}`)).data}async getQuote(){return(await o.get(`${a}quote`)).data}}const u=new p({}),l={burger:document.querySelector(".js-burger"),filter:document.querySelector(".js-filter"),gallery:document.querySelector(".js-gallery")};function d(r){return r.map(({filter:s,name:i,imgURL:n})=>`<li data-subfilter="${i}" class="exercises-item">
      <a class="exercises-item-container" href="">
        <img class="exercises-item-image" src="${n}" alt="${i}" />
        <div class="exercises-proprties-container">
          <h4 class="exercises-item-name">${i}</h4>
          <p class="exercises-item-type">${s}</p>
        </div>
      </a>
    </li>`).join("")}async function g(){const r=await u.getFilters();l.gallery.innerHTML=d(r.results)}function m(r){r.target.hasAttribute("data-filter")&&(u.filter=r.target.dataset.filter,g())}function y(r){}function h(r){}l.filter.addEventListener("click",m);l.gallery.addEventListener("click",y);l.gallery.addEventListener("click",h);async function b(){const r=await u.getFilters();l.gallery.innerHTML=d(r.results)}b();
//# sourceMappingURL=commonHelpers2.js.map
